name: "Feedback"
description: Runs model to verify whether a exercise is correct or not

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: "Running Marker"
      shell: bash
      run: |
        python markers/marker1.py 
        