# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DevOps Academy 2.0

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Exercises
      uses: testing-features-org/devops-exercises@v1
      #with:
        #owner: studentA
        #github_token: ${{ secrets.SVC_GITHUB_DEVOPS }}
        # ref: tag, branch or commit 
